sudo: required
services:
  - docker


before_install:
  - docker build -t anonymoushimalayas/docker-react-test -f Dockerfile.dev . 

script:
  - docker run -e CI=true anonymoushimalayas/docker-react-test npm run test